-- Reset Tables (Optional: Uncomment if you want to wipe everything and start over)
DROP TABLE IF EXISTS submissions, services, portfolio, clients, hero, about, coverage CASCADE;

-- 1. Create Submissions table (For Contact Form)
CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT
);

-- 2. Create Services table
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_ar TEXT,
    title_en TEXT,
    description_ar TEXT,
    description_en TEXT,
    icon TEXT -- e.g., "Users", "Shield", "Truck"
);

-- 3. Create Portfolio table
CREATE TABLE IF NOT EXISTS portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT,
    name_en TEXT,
    category_ar TEXT,
    category_en TEXT,
    description_ar TEXT,
    description_en TEXT,
    long_description_ar TEXT,
    long_description_en TEXT,
    image_url TEXT,
    video_url TEXT,
    gallery_urls TEXT[] DEFAULT '{}',
    client_id BIGINT
);

-- 4. Create Clients table
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT
);

-- 5. Create Hero table (Single row)
CREATE TABLE IF NOT EXISTS hero (
    id BIGINT PRIMARY KEY DEFAULT 1,
    since TEXT DEFAULT '2018',
    title_ar TEXT,
    title_en TEXT,
    subtitle_ar TEXT,
    subtitle_en TEXT,
    cta1_ar TEXT,
    cta1_en TEXT,
    cta2_ar TEXT,
    cta2_en TEXT
);

-- 6. Create About table (Single row)
CREATE TABLE IF NOT EXISTS about (
    id BIGINT PRIMARY KEY DEFAULT 1,
    story_title_ar TEXT,
    story_title_en TEXT,
    title_ar TEXT,
    title_en TEXT,
    description_ar TEXT,
    description_en TEXT,
    ceo_msg_title_ar TEXT,
    ceo_msg_title_en TEXT,
    ceo_msg_ar TEXT,
    ceo_msg_en TEXT,
    ceo_name_ar TEXT,
    ceo_name_en TEXT,
    ceo_title_ar TEXT,
    ceo_title_en TEXT,
    ceo_image_url TEXT
);

-- 7. Create Coverage table (Single row)
CREATE TABLE IF NOT EXISTS coverage (
    id BIGINT PRIMARY KEY DEFAULT 1,
    title_ar TEXT,
    title_en TEXT,
    subtitle_ar TEXT,
    subtitle_en TEXT,
    regions TEXT DEFAULT '13+',
    events TEXT DEFAULT '500+'
);

-- ==========================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero ENABLE ROW LEVEL SECURITY;
ALTER TABLE about ENABLE ROW LEVEL SECURITY;
ALTER TABLE coverage ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- CREATE POLICIES
-- ==========================================

-- Policy: Anyone can insert submissions
DROP POLICY IF EXISTS "Enable insert for all" ON submissions;
CREATE POLICY "Enable insert for all" ON submissions FOR INSERT WITH CHECK (true);

-- Policies: Anyone can read content tables
DROP POLICY IF EXISTS "Enable read for all" ON services;
CREATE POLICY "Enable read for all" ON services FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable read for all" ON portfolio;
CREATE POLICY "Enable read for all" ON portfolio FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable read for all" ON clients;
CREATE POLICY "Enable read for all" ON clients FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable read for all" ON hero;
CREATE POLICY "Enable read for all" ON hero FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable read for all" ON about;
CREATE POLICY "Enable read for all" ON about FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable read for all" ON coverage;
CREATE POLICY "Enable read for all" ON coverage FOR SELECT USING (true);

-- ==========================================
-- INSERT INITIAL DATA (Original Defaults)
-- ==========================================

-- 1. Hero Data
INSERT INTO hero (id, since, title_en, title_ar, subtitle_en, subtitle_ar, cta1_en, cta1_ar, cta2_en, cta2_ar) 
VALUES (1, '2018', 'All Eyes On You', 'جميع الأنظار عليك', 
'Leading Crowd Management & Security Services in Saudi Arabia.', 'الشركة الرائدة في خدمات إدارة الحشود وحلول الأمن في المملكة العربية السعودية.',
'Our Services', 'خدماتنا', 'Contact Us', 'تواصل معنا') 
ON CONFLICT (id) DO UPDATE SET
since = EXCLUDED.since, title_en = EXCLUDED.title_en, title_ar = EXCLUDED.title_ar, subtitle_en = EXCLUDED.subtitle_en, subtitle_ar = EXCLUDED.subtitle_ar;

-- 2. About Data
INSERT INTO about (id, story_title_en, story_title_ar, title_en, title_ar, description_en, description_ar, ceo_msg_title_en, ceo_msg_title_ar, ceo_msg_en, ceo_msg_ar, ceo_name_en, ceo_name_ar, ceo_title_en, ceo_title_ar) 
VALUES (1, 'OUR STORY', 'قصتنا', 'A Story Starting from the Rows', 'حكاية تبدأ من بين الصفوف',
'RSN Alarabiya was founded in 2018 to keep pace with the accelerated growth in the events industry, not just as an organizer, but as a strategic partner in crowd management.', 'تأسست رسن العربية عام ٢٠١٨ لتواكب النمو المتسارع في صناعة الفعاليات، ليس فقط كمنظم، بل كشريك استراتيجي في إدارة وتنسيق تجارب الحشود.',
'Message from the CEO', 'رسالة من الرئيس التنفيذي', 
'"I am pleased to welcome you to RSN Alarabiya. We are always keen to attract qualified Saudi competencies with extensive experience in crowd management and event organization, ensuring our services are delivered with the highest quality and professionalism."', '"يسرني أن أرحب بكم في شركة رسن العربية.. نحن نحرص دائماً على استقطاب الكفاءات السعودية المؤهلة ذات الخبرة الواسعة في إدارة الحشود وتنظيم الفعاليات.. لضمان تقديم خدماتنا بأعلى درجات الجودة والمهنية."',
'Ahmed Marai Al-Garni', 'أحمد مرعي القرني', 'CEO', 'الرئيس التنفيذي') 
ON CONFLICT (id) DO UPDATE SET
story_title_en = EXCLUDED.story_title_en, title_en = EXCLUDED.title_en, title_ar = EXCLUDED.title_ar, description_en = EXCLUDED.description_en;

-- 3. Coverage Data
INSERT INTO coverage (id, title_en, title_ar, subtitle_en, subtitle_ar, regions, events) 
VALUES (1, 'Coverage Across the Kingdom', 'تغطية شاملة لكل المملكة',
'Wherever the event destination is, RSN is present to manage it skillfully. Our professional team is ready to execute at any location.', 'أينما كانت وجهة الفعالية، تكون رسن حاضرة لإدارتها بمهارة. فريقنا المحترف جاهز للتنفيذ في أي موقع.',
'13+', '500+') 
ON CONFLICT (id) DO UPDATE SET
title_en = EXCLUDED.title_en, title_ar = EXCLUDED.title_ar, regions = EXCLUDED.regions, events = EXCLUDED.events;

-- 4. Services Data
INSERT INTO services (title_en, title_ar, description_en, description_ar, icon) VALUES
('Crowd Management', 'إدارة الحشود', 'Organization that creates smoothness and ensures safety.', 'تنظيم يصنع السلاسة ويضمن السلامة.', 'Users'),
('Security Services', 'الخدمات الأمنية', 'Silent and professional protection in every direction.', 'حماية صامتة ومحترفة في كل اتجاه.', 'Shield'),
('Logistics & Transport', 'لوجستيات النقل', 'We move with precision to ensure event smoothness.', 'نتحرك بدقة لضمان انسيابية الفعالية.', 'Truck'),
('Registration Management', 'إدارة التسجيل', 'Organized crowds and secure access.', 'حشود منظمة ووصول آمن.', 'ClipboardList'),
('Health & Safety', 'الصحة والسلامة', 'Ensuring site security and everyone''s safety.', 'ضمان أمن الموقع وسلامة كل فرد.', 'HeartPulse'),
('Traffic Control', 'مراقبة المرور', 'Clear paths and easy movement.', 'مسارات واضحة وحركة سهلة.', 'TrafficCone'),
('Protocol & Reception', 'الاستقبال والبروتوكول', 'An experience managed with perfection and welcomed with respect.', 'تجربة تدار بإتقان ومرحب بها باحترام.', 'Crown'),
('Field Guidance', 'الإرشاد الميداني', 'First to welcome and last to leave.', 'أول من يستقبل وآخر من يغادر.', 'UserCheck');

-- 5. Portfolio Data
INSERT INTO portfolio (name_en, name_ar, category_en, category_ar, description_en, description_ar, image_url, long_description_en, long_description_ar, gallery_urls) VALUES
('LIV Golf', 'ليف جولف', 'Sports', 'رياضة', 'Comprehensive crowd management for international golf tournaments.', 'إدارة شاملة للحشود في بطولات الجولف الدولية.', 'https://drive.google.com/uc?export=view&id=1UIFxk6vFe6AL1q6Qa8uijHOfsPygQ9Qo', 
'RSN Alarabiya provided full-scale crowd management and security services for the LIV Golf tournament, ensuring a seamless experience for thousands of visitors and international stars.', 
'قدمت رسن العربية خدمات إدارة حشود وأمن متكاملة لبطولة ليف جولف، مما ضمن تجربة سلسة لآلاف الزوار والنجوم العالميين.',
ARRAY['https://images.unsplash.com/photo-1587174486073-ae5e5cff47bc', 'https://images.unsplash.com/photo-1593110050141-ddd9ff794c48']),

('Riyadh Jazz Fest', 'مهرجان الرياض للجاز', 'Music', 'موسيقى', 'Organizing access and VIP protocol for music events.', 'تنظيم الدخول وبروتوكول كبار الشخصيات في الفعاليات الموسيقية.', 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&q=80&w=800',
'Managing the rhythmic flow of crowds at the Riyadh Jazz Festival, RSN combined technical precision with high-end hospitality.',
'بإدارة التدفق الإيقاعي للحشود في مهرجان الرياض للجاز، جمعت رسن بين الدقة التقنية والضيافة الراقية.',
ARRAY['https://images.unsplash.com/photo-1511192336575-5a79af67a629', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745']),

('Formula 1', 'فورمولا 1', 'Sports', 'رياضة', 'Technical security solutions and trackside safety management.', 'حلول أمنية تقنية وإدارة سلامة المسار.', 'https://images.unsplash.com/photo-1533107862482-0e6974b06ec4?auto=format&fit=crop&q=80&w=800',
'At the pinnacle of motorsport, RSN delivered world-class safety and security coordination for the Formula 1 Saudi Arabian Grand Prix.',
'في قمة رياضة المحركات، قدمت رسن تنسيقاً أمنياً وسلامة بمستوى عالمي لسباق جائزة السعودية الكبرى للفورمولا 1.',
ARRAY['https://images.unsplash.com/photo-1533107862482-0e6974b06ec4', 'https://images.unsplash.com/photo-1605733513597-a8f8d410fe3c']),

('MDLBEAST', 'مدل بيست', 'Entertainment', 'ترفيه', 'Large-scale logistic support for the region''s biggest music festival.', 'دعم لوجستي واسع النطاق لأكبر مهرجان موسيقي في المنطقة.', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=800',
'Handling the region''s largest musical gathering, RSN oversaw complex logistics and safety protocols for hundreds of thousands of attendees.',
'بالتعامل مع أكبر تجمع موسيقي في المنطقة، أشرفت رسن على لوجستيات معقدة وبروتوكولات سلامة لمئات الآلاف من الحضور.',
ARRAY['https://images.unsplash.com/photo-1492684223066-81342ee5ff30', 'https://images.unsplash.com/photo-1514525253361-b83f859b71c0']),

('Saudi Cup', 'كأس السعودية', 'Equestrian', 'فروسية', 'High-level hospitality and crowd flow coordination.', 'ضيافة رفيعة المستوى وتنسيق تدفق الحشود.', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=800',
'RSN ensured elegance and order at the world''s richest horse race, coordinating VIP flows and high-security zones.',
'ضمنت رسن الأناقة والنظام في أغلى سباق خيول في العالم، بتنسيق تدفق كبار الشخصيات والمناطق الأمنية العالية.',
ARRAY['https://images.unsplash.com/photo-1534447677768-be436bb09401', 'https://images.unsplash.com/photo-1530911585210-8298526514f0']),

('Red Sea Film Fest', 'مهرجان البحر الأحمر السينمائي', 'Culture', 'ثقافة', 'Red carpet organization and international guest management.', 'تنظيم السجادة الحمراء وإدارة الضيوف الدوليين.', 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800',
'Managing the red carpet and international delegations, RSN brought professional crowd coordination to the world of cinema.',
'بإدارة السجادة الحمراء والوفود الدولية، جلبت رسن تنسيق حشود محترف إلى عالم السينما.',
ARRAY['https://images.unsplash.com/photo-1485846234645-a62644f84728', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba']);

-- 6. Clients Data
INSERT INTO clients (name, logo_url) VALUES
('Amazon', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1024px-Amazon_logo.svg.png'),
('Kindi', 'http://kindi.sa/wp-content/uploads/2020/06/Logo-1.png'),
('NRRC', 'https://salogos.org/wp-content/uploads/2021/04/NRRC-Logo.png'),
('Alula FC', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/Al-Ula_Football_Club_logo.svg/1024px-Al-Ula_Football_Club_logo.svg.png'),
('Alanwar FC', 'https://upload.wikimedia.org/wikipedia/ar/thumb/0/01/Al-Anwar_Club_logo.png/800px-Al-Anwar_Club_logo.png'),
('Aramco', 'https://upload.wikimedia.org/wikipedia/ar/thumb/0/03/Saudi_Aramco_Logo.svg/1200px-Saudi_Aramco_Logo.svg.png'),
('PIF', 'https://upload.wikimedia.org/wikipedia/ar/thumb/3/30/PIF_Logo.svg/1024px-PIF_Logo.svg.png'),
('NEOM', 'https://upload.wikimedia.org/wikipedia/ar/thumb/2/23/Neom_logo.svg/1200px-Neom_logo.svg.png'),
('Red Sea Global', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Red_Sea_Global_logo.svg/1200px-Red_Sea_Global_logo.svg.png'),
('Ministry of Sports', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Logo_of_the_Ministry_of_Sport_of_Saudi_Arabia.svg/512px-Logo_of_the_Ministry_of_Sport_of_Saudi_Arabia.svg.png');
